-- ═══════════════════════════════════════════════════════════════════
-- Boutique · Esquema Supabase
-- Ejecutar este script en Supabase Dashboard > SQL Editor
-- ═══════════════════════════════════════════════════════════════════

-- ── Tabla profiles (vinculada a auth.users) ────────────────────────
create table if not exists public.profiles (
  id uuid references auth.users (id) on delete cascade primary key,
  nombre text,
  rol text not null default 'cliente' check (rol in ('admin', 'cliente')),
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;

-- ── Helper: verificar si el usuario autenticado es admin ───────────
-- (se crea DESPUÉS de profiles porque es lenguaje SQL y se valida al crearse)
create or replace function public.is_admin()
returns boolean
language sql
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and rol = 'admin'
  );
$$;

-- ── Trigger: crear el perfil automáticamente al registrarse ────────
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, nombre, rol)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'nombre', split_part(new.email, '@', 1)),
    coalesce(new.raw_user_meta_data ->> 'rol', 'cliente')
  );
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- ── Políticas de profiles ──────────────────────────────────────────
create policy "select own profile" on public.profiles
  for select using (auth.uid() = id);

create policy "update own profile" on public.profiles
  for update using (auth.uid() = id);

create policy "admin select all profiles" on public.profiles
  for select using (public.is_admin());

-- ── Tabla products ─────────────────────────────────────────────────
create table if not exists public.products (
  id bigint generated by default as identity primary key,
  nombre text not null,
  precio numeric(12, 2) not null default 0,
  imagen text,
  descripcion text,
  categoria text,
  created_at timestamptz not null default now()
);

alter table public.products enable row level security;

-- ── Políticas de products ──────────────────────────────────────────
-- Lectura pública del catálogo
create policy "public read products" on public.products
  for select using (true);

-- Escritura (crear, editar, eliminar) solo para admin
create policy "admin insert products" on public.products
  for insert with check (public.is_admin());

create policy "admin update products" on public.products
  for update using (public.is_admin());

create policy "admin delete products" on public.products
  for delete using (public.is_admin());

-- ── Storage: bucket público para imágenes de productos ─────────────
insert into storage.buckets (id, name, public)
values ('product-images', 'product-images', true)
on conflict (id) do nothing;

-- Lectura pública
create policy "public read product images" on storage.objects
  for select using (bucket_id = 'product-images');

-- Subida/actualización/borrado solo para usuarios autenticados
create policy "authenticated upload product images" on storage.objects
  for insert to authenticated
  with check (bucket_id = 'product-images');

create policy "authenticated update product images" on storage.objects
  for update to authenticated
  using (bucket_id = 'product-images');

create policy "authenticated delete product images" on storage.objects
  for delete to authenticated
  using (bucket_id = 'product-images');

-- ── Crear usuario admin (después de registrarse desde la app):
-- UPDATE public.profiles SET rol = 'admin'
-- WHERE id = (SELECT id FROM auth.users WHERE email = 'admin@boutique.com');